### PR TITLE
Interactable chars

### PR DESCRIPTION
**Pull request by tigleym**

### CODE REVIEW

**Comment by NightlySide** [comment]
I don't know which part of the `data/chunks.ron` file to keep, so I won't be able to merge this branch

**Comment by cdsupina** [comment]
> I don't know which part of the `data/chunks.ron` file to keep, so I won't be able to merge this branch

@tigleym do you want to change collected letters to be stored in a resource? Then, if you prefer, I can merge it with master to make sure chunks.ron is good.

**Comment by tigleym** [comment]
> @tigleym do you want to change collected letters to be stored in a resource? Then, if you prefer, I can merge it with master to make sure chunks.ron is good.

Yep I can make that change! Shouldn't be too hard.

**Comment by NightlySide** [comment]
There are still conflicts, I'll let you merge this branch

**Pull request merged**
